version: '3.1'

services:
  postgresql:
    image: postgres:11-alpine
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5435:5432
    networks:
      - user-service
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env

volumes:
  postgresql-data:
    driver: local
