version: '3.1'

services:
  postgresql:
    image: postgres:latest
    volumes:
      - postgresql-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
    networks:
      - postgresql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass admin
    volumes:
      - redis:/data

  mongo:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${EVENT_STORAGE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${EVENT_STORAGE_PASSWORD}
    env_file:
      - .env
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${EVENT_STORAGE_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${EVENT_STORAGE_PASSWORD}
    env_file:
      - .env

  centrifugo:
    image: centrifugo/centrifugo:latest
    container_name: centrifugo
    volumes:
      - ./centrifugo-config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8000:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

volumes:
  postgresql-data:
    driver: local
  redis:
    driver: local
  mongo-data:
    driver: local

networks:
  postgresql:
    driver: bridge
