version: '3.1'

services:
  postgresql:
    image: postgres:11-alpine
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
    networks:
      - postgresql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env

#  mongo:
#    image: mongo:4.4-bionic
#    restart: always
#    ports:
#      - 27018:27017
#    volumes:
#      - mongo-data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${EVENT_STORAGE_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${EVENT_STORAGE_PASSWORD}
#    env_file:
#      - .env
#
#  mongo-express:
#    image: mongo-express:0.54
#    restart: always
#    ports:
#      - 8082:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: ${EVENT_STORAGE_USERNAME}
#      ME_CONFIG_MONGODB_ADMINPASSWORD: ${EVENT_STORAGE_PASSWORD}
#    env_file:
#      - .env

  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v4
    volumes:
      - ./centrifugo-config.json:/centrifugo/config.json
    command: centrifugo -c config.json --client_insecure
    ports:
      - 8000:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

volumes:
  postgresql-data:
    driver: local
  mongo-data:
    driver: local

networks:
  postgresql:
    driver: bridge
